version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum update -y
      - sudo yum install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /usr/share/nginx/html

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/*
